import type { AssumptionCard, CharSession, Decision } from "./types";

function slugify(text: string) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48);
}

/** Matt Pocock ADR gate: hard to reverse + surprising + real trade-off.
 * Heuristic for hack: keep + recommended keep + assumption length / fork. */
function qualifiesAsAdr(card: AssumptionCard, decision: Decision): boolean {
  if (decision !== "keep") return false;
  if (card.kind === "fork") return true;
  if (card.recommendedStance === "keep" && card.assumption.length > 40) return true;
  return card.category.toLowerCase().includes("architecture") ||
    card.category.toLowerCase().includes("distribution") ||
    card.category.toLowerCase().includes("monetization");
}

export function buildApplyArtifacts(session: CharSession): {
  charMd: string;
  agentsMd: string;
  adrs: { path: string; content: string }[];
} {
  const kept: AssumptionCard[] = [];
  const killed: AssumptionCard[] = [];
  const researched: AssumptionCard[] = [];
  const skipped: AssumptionCard[] = [];

  for (const card of session.cards) {
    if (card.kind === "research_brief") {
      researched.push(card);
      continue;
    }
    const d = session.decisions[card.id];
    if (d === "keep") kept.push(card);
    else if (d === "kill") killed.push(card);
    else if (d === "skipped") skipped.push(card);
    else if (d === "research") researched.push(card);
  }

  const adrs: { path: string; content: string }[] = [];
  let n = 1;
  const adrLines: string[] = [];

  for (const card of kept) {
    if (!qualifiesAsAdr(card, "keep")) continue;
    const num = String(n).padStart(4, "0");
    const slug = slugify(card.assumption);
    const path = `docs/adr/${num}-${slug}.md`;
    const content = `# ${card.assumption}

Category: ${card.category}. Grounded: ${card.grounded}.

We keep this assumption: ${card.rationale}

Status: accepted
`;
    adrs.push({ path, content });
    adrLines.push(`- ADR ${num}: ${card.assumption} (\`${path}\`)`);
    n += 1;
  }

  const charMd = `# CHAR · Match Sheet

**Pitch:** ${session.pitch}

**Repo:** ${session.repoUrl || "(pitch-only)"}

**Session:** ${session.id}
**Updated:** ${new Date().toISOString()}

## Kept (load-bearing)

${kept.map((c) => `- **${c.assumption}** — ${c.rationale}`).join("\n") || "_None_"}

## Killed (soft / false)

${killed.map((c) => `- **${c.assumption}** — ${c.rationale}`).join("\n") || "_None_"}

## Research briefs

${researched
  .map((c) => `- **${c.assumption}** — ${c.findings || c.rationale}`)
  .join("\n") || "_None_"}

## Skipped (That’s enough)

${skipped.map((c) => `- ${c.assumption}`).join("\n") || "_None_"}

## ADRs written

${adrLines.join("\n") || "_None qualified_"}

---
Generated by CHAR. Build only what survived.
`;

  const agentsMd = `# Agent constraints (from CHAR)

When working in this repository, respect the following decisions from the latest CHAR session:

## Must honor (kept)

${kept.map((c) => `- ${c.assumption}`).join("\n") || "- (none)"}

## Do not build toward (killed)

${killed.map((c) => `- ${c.assumption}`).join("\n") || "- (none)"}

## Rule

Build only what survived CHAR. If a task conflicts with a kept assumption, stop and ask.
`;

  return { charMd, agentsMd, adrs };
}
